### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by pvitoria** [Zakobian/CT_framework_#1]
Hi!
Nice work

I think in this line should be 
delf = config.fwd_op_mod(f[:,1:2])

https://github.com/Zakobian/CT_framework_/blob/e906e57af04bc715d771ff1976fec660c100d237/Algorithms/LPD.py#L42

**Comment by Zakobian** [comment]
Hey! Didn't expect anyone to be using this, but yes this does seem like a bug I overlooked when copying down the algorithm.
