### ISSUE TITLE
Structure of each dataset

### ISSUE THREAD

**Issue by Higgins995** [Zakobian/CT_framework_#2]
Hi👋, I want to use this framework to do image reconstruction, but I am having trouble loading the dataset. Please, can you tell me What is the file structure of each dataset? Thank you!

**Comment by Higgins995** [comment]
Sorry, maybe I didn't express myself clearly. I would like to know the directory structure under each dataset folder.

**Comment by Zakobian** [comment]
The structure of the folders is basically the following (on top of what is commented in the config.py):
.
└── MAYO
    ├── test
    ├── train
    └── valid
and each of those contains items like scan_0001.npy (i.e. the actual image). Note that this framework is a little outdated and in a lot of ways unoptimized and undocumented. I aim to release a nicer version in the coming months.
